export type StateTaxConfig = {
  code: string;                    // 2-letter state code: "CA", "AZ", "TX"
  name: string;                    // Full name: "California", "Arizona", "Texas"
  hasIncomeTax: boolean;           // false for AK, FL, NV, SD, TN, TX, WA, WY, NH
  nonresidentForm: string | null;  // Display name: "Form 540NR"
  formId: string | null;           // Registry key when implemented: "f540nr", "f140nr"
  emptyFile: string | null;        // PDF filename in public/forms/empty/: "540nr.pdf"
  filledFilename: string | null;   // Suggested download name: "540nr_filled.pdf"
  implemented: boolean;            // true = full fill experience, false = coming soon
};

export const STATE_TAX_MAP: Record<string, StateTaxConfig> = {
  // ── Implemented (full fill experience) ──────────────────────────────────────
  CA: {
    code: "CA",
    name: "California",
    hasIncomeTax: true,
    nonresidentForm: "Form 540NR",
    formId: "f540nr",
    emptyFile: "540nr.pdf",
    filledFilename: "540nr_filled.pdf",
    implemented: true,
  },
  AZ: {
    code: "AZ",
    name: "Arizona",
    hasIncomeTax: true,
    nonresidentForm: "Form 140NR",
    formId: "f140nr",
    emptyFile: "az140nr.pdf",
    filledFilename: "az140nr_filled.pdf",
    implemented: true,
  },

  // ── Income-tax states -- Coming Soon ─────────────────────────────────────────
  AL: {
    code: "AL",
    name: "Alabama",
    hasIncomeTax: true,
    nonresidentForm: "Form 40NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  AR: {
    code: "AR",
    name: "Arkansas",
    hasIncomeTax: true,
    nonresidentForm: "AR1000NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  CO: {
    code: "CO",
    name: "Colorado",
    hasIncomeTax: true,
    nonresidentForm: "DR 0104PN",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  CT: {
    code: "CT",
    name: "Connecticut",
    hasIncomeTax: true,
    nonresidentForm: "CT-1040NR/PY",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  DE: {
    code: "DE",
    name: "Delaware",
    hasIncomeTax: true,
    nonresidentForm: "Form 200-02",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  GA: {
    code: "GA",
    name: "Georgia",
    hasIncomeTax: true,
    nonresidentForm: "Form 500-NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  HI: {
    code: "HI",
    name: "Hawaii",
    hasIncomeTax: true,
    nonresidentForm: "N-15",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  ID: {
    code: "ID",
    name: "Idaho",
    hasIncomeTax: true,
    nonresidentForm: "Form 43",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  IL: {
    code: "IL",
    name: "Illinois",
    hasIncomeTax: true,
    nonresidentForm: "IL-1040 + Schedule NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  IN: {
    code: "IN",
    name: "Indiana",
    hasIncomeTax: true,
    nonresidentForm: "IT-40PNR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  IA: {
    code: "IA",
    name: "Iowa",
    hasIncomeTax: true,
    nonresidentForm: "IA 126",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  KS: {
    code: "KS",
    name: "Kansas",
    hasIncomeTax: true,
    nonresidentForm: "K-40 (NR indicator)",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  KY: {
    code: "KY",
    name: "Kentucky",
    hasIncomeTax: true,
    nonresidentForm: "Form 740-NP",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  LA: {
    code: "LA",
    name: "Louisiana",
    hasIncomeTax: true,
    nonresidentForm: "IT-540B",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  ME: {
    code: "ME",
    name: "Maine",
    hasIncomeTax: true,
    nonresidentForm: "Form 1040ME + Schedule NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  MD: {
    code: "MD",
    name: "Maryland",
    hasIncomeTax: true,
    nonresidentForm: "Form 505",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  MA: {
    code: "MA",
    name: "Massachusetts",
    hasIncomeTax: true,
    nonresidentForm: "Form 1-NR/PY",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  MI: {
    code: "MI",
    name: "Michigan",
    hasIncomeTax: true,
    nonresidentForm: "MI-1040 + Schedule NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  MN: {
    code: "MN",
    name: "Minnesota",
    hasIncomeTax: true,
    nonresidentForm: "M1NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  MS: {
    code: "MS",
    name: "Mississippi",
    hasIncomeTax: true,
    nonresidentForm: "Form 80-205",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  MO: {
    code: "MO",
    name: "Missouri",
    hasIncomeTax: true,
    nonresidentForm: "MO-1040 + MO-NRI",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  MT: {
    code: "MT",
    name: "Montana",
    hasIncomeTax: true,
    nonresidentForm: "Form 2 + Schedule NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  NE: {
    code: "NE",
    name: "Nebraska",
    hasIncomeTax: true,
    nonresidentForm: "Form 1040N + Schedule III",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  NJ: {
    code: "NJ",
    name: "New Jersey",
    hasIncomeTax: true,
    nonresidentForm: "NJ-1040NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  NM: {
    code: "NM",
    name: "New Mexico",
    hasIncomeTax: true,
    nonresidentForm: "PIT-1 (same form + allocation)",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  NY: {
    code: "NY",
    name: "New York",
    hasIncomeTax: true,
    nonresidentForm: "IT-203",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  NC: {
    code: "NC",
    name: "North Carolina",
    hasIncomeTax: true,
    nonresidentForm: "D-400 + PN schedule",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  ND: {
    code: "ND",
    name: "North Dakota",
    hasIncomeTax: true,
    nonresidentForm: "ND-1NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  OH: {
    code: "OH",
    name: "Ohio",
    hasIncomeTax: true,
    nonresidentForm: "IT 1040 + Schedule of Credits",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  OK: {
    code: "OK",
    name: "Oklahoma",
    hasIncomeTax: true,
    nonresidentForm: "Form 511NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  OR: {
    code: "OR",
    name: "Oregon",
    hasIncomeTax: true,
    nonresidentForm: "OR-40-N / OR-40-P",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  PA: {
    code: "PA",
    name: "Pennsylvania",
    hasIncomeTax: true,
    nonresidentForm: "PA-40 (same form)",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  RI: {
    code: "RI",
    name: "Rhode Island",
    hasIncomeTax: true,
    nonresidentForm: "RI-1040NR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  SC: {
    code: "SC",
    name: "South Carolina",
    hasIncomeTax: true,
    nonresidentForm: "SC1040 + NR schedule",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  UT: {
    code: "UT",
    name: "Utah",
    hasIncomeTax: true,
    nonresidentForm: "TC-40 + Schedule TC-40B",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  VT: {
    code: "VT",
    name: "Vermont",
    hasIncomeTax: true,
    nonresidentForm: "IN-111 + Schedule IN-113",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  VA: {
    code: "VA",
    name: "Virginia",
    hasIncomeTax: true,
    nonresidentForm: "Form 763",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  WV: {
    code: "WV",
    name: "West Virginia",
    hasIncomeTax: true,
    nonresidentForm: "IT-140NRC",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  WI: {
    code: "WI",
    name: "Wisconsin",
    hasIncomeTax: true,
    nonresidentForm: "Form 1NPR",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  DC: {
    code: "DC",
    name: "District of Columbia",
    hasIncomeTax: true,
    nonresidentForm: "D-40B",
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },

  // ── No state income tax ──────────────────────────────────────────────────────
  AK: {
    code: "AK",
    name: "Alaska",
    hasIncomeTax: false,
    nonresidentForm: null,
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  FL: {
    code: "FL",
    name: "Florida",
    hasIncomeTax: false,
    nonresidentForm: null,
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  NV: {
    code: "NV",
    name: "Nevada",
    hasIncomeTax: false,
    nonresidentForm: null,
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  SD: {
    code: "SD",
    name: "South Dakota",
    hasIncomeTax: false,
    nonresidentForm: null,
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  TN: {
    code: "TN",
    name: "Tennessee",
    hasIncomeTax: false,
    nonresidentForm: null,
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  TX: {
    code: "TX",
    name: "Texas",
    hasIncomeTax: false,
    nonresidentForm: null,
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  WA: {
    code: "WA",
    name: "Washington",
    hasIncomeTax: false,
    nonresidentForm: null,
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
  WY: {
    code: "WY",
    name: "Wyoming",
    hasIncomeTax: false,
    nonresidentForm: null,
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },

  // ── Special case: no wage income tax ────────────────────────────────────────
  // W-2 wages are not taxed; treated as no-income-tax for our purposes.
  NH: {
    code: "NH",
    name: "New Hampshire",
    hasIncomeTax: false,
    nonresidentForm: null,
    formId: null,
    emptyFile: null,
    filledFilename: null,
    implemented: false,
  },
};

/** Case-insensitive lookup. Returns undefined for unknown codes. */
export function getStateTaxConfig(code: string): StateTaxConfig | undefined {
  return STATE_TAX_MAP[code.toUpperCase()];
}

/** Returns true when the state levies no income tax on W-2 wages. */
export function isNoIncomeTaxState(code: string): boolean {
  const config = getStateTaxConfig(code);
  return config !== undefined && !config.hasIncomeTax;
}

/** Returns all states with a full fill experience (implemented === true). */
export function getImplementedStates(): StateTaxConfig[] {
  return Object.values(STATE_TAX_MAP).filter((s) => s.implemented);
}
